swagger: '2.0'
info:
  title: 01-helloworld API
  version: '1.0.0'
  description: >
    HelloWorld API
consumes:
  - application/json
produces:
  - application/json
basePath: /
host: localhost:8080
schemes:
  - http
tags:
  - name: messages
    description: A list of messages
  - name: message
    description: A message
paths:
  /:
    get:
      tags:
        - messages
      operationId: app.get_messages_root
      summary: Get messages
      responses:
        200:
          description: Return a list of messages
          schema:
            $ref: '#/definitions/Messages'

  /messages:
    get:
      tags:
        - messages
      operationId: app.get_messages
      summary: Get messages
      responses:
        200:
          description: Return a list of messages
          schema:
            $ref: '#/definitions/Messages'

  /messages/{id}:
    get:
      tags:
        - message
      operationId: app.get_message
      summary: get a message
      parameters:
        - in: path
          name: id
          type: integer
          description: The id of the message
          required: true
      responses:
        200:
          description: Return a message
          schema:
            $ref: '#/definitions/Message'
        404:
          description: Not found

definitions:
  Message:
    type: object
    required:
      - msg
    properties:
      msg:
        type: string
        description: A message
        example: 'Hello World'
        minLength: 1
        maxLength: 100
    example:
      msg: 'Hello World'

  Messages:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
    example:
      - msg: 'Hello World 1'
      - msg: 'Hello World 2'
      - msg: 'Hello World 3'
